import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Physical AI Textbook Sidebar with 4 core modules
  textbookSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      link: {
        type: 'generated-index',
        title: 'ROS 2 Fundamentals',
        description: 'Learn the fundamentals of Robot Operating System 2 (ROS 2), including nodes, topics, services, and actions.',
        slug: '/module-1-ros2',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-1-ros2'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Unity Simulation',
      link: {
        type: 'generated-index',
        title: 'Gazebo & Unity Simulation',
        description: 'Master robot simulation using Gazebo Classic, Gazebo Fortress, and Unity with ROS integration.',
        slug: '/module-2-gazebo-unity',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-2-gazebo-unity'},
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Platform',
      link: {
        type: 'generated-index',
        title: 'NVIDIA Isaac Platform',
        description: 'Explore NVIDIA Isaac Sim and Isaac SDK for advanced robot simulation and AI development.',
        slug: '/module-3-isaac',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-3-isaac'},
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Models',
      link: {
        type: 'generated-index',
        title: 'Vision-Language-Action (VLA) Models',
        description: 'Learn about cutting-edge VLA models for embodied AI and humanoid robotics.',
        slug: '/module-4-vla',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-4-vla'},
      ],
    },
  ],
};

export default sidebars;
